<?php
/**
 * Title: Home Field Photos Section
 * Slug: rarc-theme/home-field-photos
 * Categories: rarc-theme, rarc-home-sections
 */
?>
<!-- wp:group {"align":"full","anchor":"events","className":"rarc-section","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull rarc-section"><div class="wp-block-group__inner-container"><!-- wp:group {"align":"wide","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignwide"><!-- wp:rarc/carousel {"variant":"full","eyebrow":"Member photography","heading":"Field photos with room to grow.","intro":"The carousel can start with verified open-license images, then expand naturally as members contribute aircraft, field, and event photography.","slides":[{"imageUrl":"https://commons.wikimedia.org/wiki/Special:FilePath/E-flite_UMX_Yak_54_3D_at_the_field_IMG_4427_FRD.jpg?width=1200","alt":"Remote control aircraft staged at a flying field","title":"Aircraft on the flight line","caption":"CC placeholder from Wikimedia Commons: E-flite UMX Yak 54 3D at the field."},{"imageUrl":"https://commons.wikimedia.org/wiki/Special:FilePath/In_control%2C_Garvaghy_-_geograph.org.uk_-_1225055.jpg?width=1200","alt":"Pilot controlling a model aircraft outdoors","title":"Member activity and instruction","caption":"CC BY-SA placeholder from Wikimedia Commons / Geograph: In control, Garvaghy."},{"imageUrl":"https://commons.wikimedia.org/wiki/Special:FilePath/Model_aircraft_flying%2C_Lower_Fields%2C_Napton_-_geograph.org.uk_-_1272769.jpg?width=1200","alt":"Model aircraft flying over open fields","title":"Open-field flying","caption":"CC BY-SA placeholder from Wikimedia Commons / Geograph: Model aircraft flying, Lower Fields, Napton."},{"imageUrl":"https://commons.wikimedia.org/wiki/Special:FilePath/Spring_flying_at_KILY_club_field%2C_Elim%C3%A4ki_%282475846526%29.jpg?width=1200","alt":"RC club field with members and aircraft","title":"Club field context","caption":"CC BY placeholder from Wikimedia Commons: spring flying at a club field."},{"imageUrl":"https://commons.wikimedia.org/wiki/Special:FilePath/Radio_controlled_model_aircraft_event_-_geograph.org.uk_-_3992818.jpg?width=1200","alt":"Radio controlled aircraft event at a field","title":"Event-ready photography","caption":"CC BY-SA placeholder from Wikimedia Commons / Geograph: radio controlled model aircraft event."}]} /--></div>
<!-- /wp:group --></div></div>
<!-- /wp:group -->
