<?php
/**
 * Title: Home Events And Stories Section
 * Slug: rarc-theme/home-events-stories
 * Categories: rarc-theme, rarc-home-sections
 */
?>
<!-- wp:group {"align":"full","className":"rarc-section","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull rarc-section is-layout-constrained wp-block-group-is-layout-constrained"><!-- wp:group {"align":"wide","className":"rarc-plain-cta"} -->
<div class="wp-block-group alignwide rarc-plain-cta is-layout-flow wp-block-group-is-layout-flow"><!-- wp:group {"className":"rarc-section-head"} --><div class="wp-block-group rarc-section-head is-layout-flow wp-block-group-is-layout-flow"><!-- wp:group --><div class="wp-block-group is-layout-flow wp-block-group-is-layout-flow"><!-- wp:paragraph {"className":"rarc-eyebrow"} --><p class="rarc-eyebrow">Events and stories</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2 class="wp-block-heading">This month at the field.</h2><!-- /wp:heading --></div><!-- /wp:group --><!-- wp:paragraph --><p>The homepage only needs enough detail to show that the club has a real calendar, real people, and a clear next step for visitors who want more detail.</p><!-- /wp:paragraph --></div><!-- /wp:group -->

<!-- wp:group {"className":"rarc-story-layout","layout":{"type":"grid"}} -->
<div class="wp-block-group rarc-story-layout is-layout-grid wp-block-group-is-layout-grid"><!-- wp:group {"className":"rarc-story-intro"} --><div class="wp-block-group rarc-story-intro is-layout-flow wp-block-group-is-layout-flow"><!-- wp:paragraph --><p>Keep the front page summary practical: what is happening next, whether a newcomer can comfortably show up, and where the fuller recap or event details live.</p><!-- /wp:paragraph --><!-- wp:group {"className":"rarc-story-state"} --><div class="wp-block-group rarc-story-state is-layout-flow wp-block-group-is-layout-flow"><!-- wp:paragraph --><p><strong>Weather and field-condition updates should post before driving time.</strong></p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Use this slim note for same-day changes, soft-field closures, or a reminder that guest visits are easiest during scheduled intro mornings.</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:buttons {"className":"rarc-actions"} --><div class="wp-block-buttons rarc-actions"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#contact">Ask about upcoming events</a></div><!-- /wp:button --><!-- wp:button {"className":"is-style-outline"} --><div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="#visit">See the membership path</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group -->

<!-- wp:group {"className":"rarc-story-columns","layout":{"type":"grid"}} -->
<div class="wp-block-group rarc-story-columns is-layout-grid wp-block-group-is-layout-grid"><!-- wp:group {"className":"rarc-story-column"} --><div class="wp-block-group rarc-story-column is-layout-flow wp-block-group-is-layout-flow"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Upcoming events</h3><!-- /wp:heading --><!-- wp:group {"className":"rarc-story-list"} --><div class="wp-block-group rarc-story-list is-layout-flow wp-block-group-is-layout-flow"><!-- wp:group {"className":"rarc-story-item"} --><div class="wp-block-group rarc-story-item is-layout-flow wp-block-group-is-layout-flow"><!-- wp:paragraph {"className":"rarc-story-meta"} --><p class="rarc-story-meta">July 13 · Intro flight morning</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><strong>New visitors can meet members, walk the flight line, and see trainer setups before noon flying starts.</strong></p><!-- /wp:paragraph --><!-- wp:paragraph --><p>A low-pressure first-visit window with parking guidance, flight-line orientation, and informal mentoring for newcomers.</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:group {"className":"rarc-story-item"} --><div class="wp-block-group rarc-story-item is-layout-flow wp-block-group-is-layout-flow"><!-- wp:paragraph {"className":"rarc-story-meta"} --><p class="rarc-story-meta">July 27 · Scale and sport showcase</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><strong>Members bring current builds, favorite sport planes, and a few scale models for an easy summer field day.</strong></p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Useful as a homepage teaser, with arrival timing, pilot notes, and any rain call living on the interior page.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --></div><!-- /wp:group -->

<!-- wp:group {"className":"rarc-story-column"} --><div class="wp-block-group rarc-story-column is-layout-flow wp-block-group-is-layout-flow"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Recent stories</h3><!-- /wp:heading --><!-- wp:group {"className":"rarc-story-list"} --><div class="wp-block-group rarc-story-list is-layout-flow wp-block-group-is-layout-flow"><!-- wp:group {"className":"rarc-story-item"} --><div class="wp-block-group rarc-story-item is-layout-flow wp-block-group-is-layout-flow"><!-- wp:paragraph {"className":"rarc-story-meta"} --><p class="rarc-story-meta">Field notes</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><strong>How visiting pilots move from parking to pit area without guessing where to check in.</strong></p><!-- /wp:paragraph --><!-- wp:paragraph --><p>A practical article that can combine plain text, one or two aligned photos, and the retained carousel-card pattern.</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:group {"className":"rarc-story-item"} --><div class="wp-block-group rarc-story-item is-layout-flow wp-block-group-is-layout-flow"><!-- wp:paragraph {"className":"rarc-story-meta"} --><p class="rarc-story-meta">Member feature</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><strong>A short build recap for a favorite electric sport model, with just enough imagery to feel personal.</strong></p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Use the interior module for the fuller sequence instead of stacking another full-width homepage widget.</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:group --></div><!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
